### PR TITLE
IMPROVE DOCS FOR THIS AMAZING PROJECT!!1!

### PR DESCRIPTION
**Pull request by twobackfromtheend**

### CODE REVIEW

**Comment by AlexanderBelooussov** [comment]
CANT WAIT TO KNOW WHAT IS GOING ON IN THIS AMAZING PROJECT WITH MORE DOOOOOCS!!!!1!!

**Comment by ViliamVadocz** [comment]
LGTM 🥴

**Comment by twobackfromtheend** [comment]
Can we rename this project to 🔥🦙

**Comment by AlexanderBelooussov** [comment]
pls

**Pull request closed without merging**
